const currencies = [
  { code: "USD", name: "US Dollar", countryCode: "US" },
  { code: "EUR", name: "Euro", countryCode: "EU" },
  { code: "GBP", name: "British Pound", countryCode: "GB" },
  { code: "INR", name: "Indian Rupee", countryCode: "IN" },
  { code: "JPY", name: "Japanese Yen", countryCode: "JP" },
  { code: "AUD", name: "Australian Dollar", countryCode: "AU" },
  { code: "CAD", name: "Canadian Dollar", countryCode: "CA" },
  { code: "CHF", name: "Swiss Franc", countryCode: "CH" },
  { code: "CNY", name: "Chinese Yuan", countryCode: "CN" },
  { code: "HKD", name: "Hong Kong Dollar", countryCode: "HK" },
  { code: "SGD", name: "Singapore Dollar", countryCode: "SG" },
  { code: "NZD", name: "New Zealand Dollar", countryCode: "NZ" },
  { code: "SEK", name: "Swedish Krona", countryCode: "SE" },
  { code: "NOK", name: "Norwegian Krone", countryCode: "NO" },
  { code: "DKK", name: "Danish Krone", countryCode: "DK" },
  { code: "PLN", name: "Polish Zloty", countryCode: "PL" },
  { code: "CZK", name: "Czech Koruna", countryCode: "CZ" },
  { code: "HUF", name: "Hungarian Forint", countryCode: "HU" },
  { code: "RON", name: "Romanian Leu", countryCode: "RO" },
  { code: "BGN", name: "Bulgarian Lev", countryCode: "BG" },
  { code: "TRY", name: "Turkish Lira", countryCode: "TR" },
  { code: "RUB", name: "Russian Ruble", countryCode: "RU" },
  { code: "UAH", name: "Ukrainian Hryvnia", countryCode: "UA" },
  { code: "AED", name: "UAE Dirham", countryCode: "AE" },
  { code: "SAR", name: "Saudi Riyal", countryCode: "SA" },
  { code: "QAR", name: "Qatari Riyal", countryCode: "QA" },
  { code: "KWD", name: "Kuwaiti Dinar", countryCode: "KW" },
  { code: "BHD", name: "Bahraini Dinar", countryCode: "BH" },
  { code: "OMR", name: "Omani Rial", countryCode: "OM" },
  { code: "JOD", name: "Jordanian Dinar", countryCode: "JO" },
  { code: "EGP", name: "Egyptian Pound", countryCode: "EG" },
  { code: "ZAR", name: "South African Rand", countryCode: "ZA" },
  { code: "NGN", name: "Nigerian Naira", countryCode: "NG" },
  { code: "KES", name: "Kenyan Shilling", countryCode: "KE" },
  { code: "GHS", name: "Ghanaian Cedi", countryCode: "GH" },
  { code: "MAD", name: "Moroccan Dirham", countryCode: "MA" },
  { code: "TND", name: "Tunisian Dinar", countryCode: "TN" },
  { code: "DZD", name: "Algerian Dinar", countryCode: "DZ" },
  { code: "ETB", name: "Ethiopian Birr", countryCode: "ET" },
  { code: "UGX", name: "Ugandan Shilling", countryCode: "UG" },
    { code: "ARS", name: "Argentine Peso", countryCode: "AR" },
  { code: "BOB", name: "Bolivian Boliviano", countryCode: "BO" },
  { code: "BRL", name: "Brazilian Real", countryCode: "BR" },
  { code: "CLP", name: "Chilean Peso", countryCode: "CL" },
  { code: "COP", name: "Colombian Peso", countryCode: "CO" },
  { code: "CRC", name: "Costa Rican Colon", countryCode: "CR" },
  { code: "DOP", name: "Dominican Peso", countryCode: "DO" },
  { code: "GTQ", name: "Guatemalan Quetzal", countryCode: "GT" },
  { code: "HNL", name: "Honduran Lempira", countryCode: "HN" },
  { code: "JMD", name: "Jamaican Dollar", countryCode: "JM" },
  { code: "MXN", name: "Mexican Peso", countryCode: "MX" },
  { code: "NIO", name: "Nicaraguan Cordoba", countryCode: "NI" },
  { code: "PAB", name: "Panamanian Balboa", countryCode: "PA" },
  { code: "PEN", name: "Peruvian Sol", countryCode: "PE" },
  { code: "PYG", name: "Paraguayan Guarani", countryCode: "PY" },
  { code: "UYU", name: "Uruguayan Peso", countryCode: "UY" },
  { code: "VES", name: "Venezuelan Bolívar", countryCode: "VE" },
  { code: "BDT", name: "Bangladeshi Taka", countryCode: "BD" },
  { code: "LKR", name: "Sri Lankan Rupee", countryCode: "LK" },
  { code: "NPR", name: "Nepalese Rupee", countryCode: "NP" },
  { code: "PKR", name: "Pakistani Rupee", countryCode: "PK" },
  { code: "MMK", name: "Myanmar Kyat", countryCode: "MM" },
  { code: "KHR", name: "Cambodian Riel", countryCode: "KH" },
  { code: "LAK", name: "Lao Kip", countryCode: "LA" },
  { code: "MNT", name: "Mongolian Tugrik", countryCode: "MN" },
  { code: "IDR", name: "Indonesian Rupiah", countryCode: "ID" },
  { code: "MYR", name: "Malaysian Ringgit", countryCode: "MY" },
  { code: "PHP", name: "Philippine Peso", countryCode: "PH" },
  { code: "THB", name: "Thai Baht", countryCode: "TH" },
  { code: "VND", name: "Vietnamese Dong", countryCode: "VN" },
  { code: "TWD", name: "New Taiwan Dollar", countryCode: "TW" },
  { code: "MOP", name: "Macanese Pataca", countryCode: "MO" },
  { code: "BND", name: "Brunei Dollar", countryCode: "BN" },
  { code: "FJD", name: "Fijian Dollar", countryCode: "FJ" },
  { code: "PGK", name: "Papua New Guinean Kina", countryCode: "PG" },
  { code: "SBD", name: "Solomon Islands Dollar", countryCode: "SB" },
  { code: "TOP", name: "Tongan Paʻanga", countryCode: "TO" },
  { code: "WST", name: "Samoan Tala", countryCode: "WS" },
  { code: "XPF", name: "CFP Franc", countryCode: "PF" },
  { code: "XCD", name: "East Caribbean Dollar", countryCode: "AG" },
    { code: "ALL", name: "Albanian Lek", countryCode: "AL" },
  { code: "AMD", name: "Armenian Dram", countryCode: "AM" },
  { code: "AOA", name: "Angolan Kwanza", countryCode: "AO" },
  { code: "AWG", name: "Aruban Florin", countryCode: "AW" },
  { code: "AZN", name: "Azerbaijani Manat", countryCode: "AZ" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", countryCode: "BA" },
  { code: "BBD", name: "Barbadian Dollar", countryCode: "BB" },
  { code: "BIF", name: "Burundian Franc", countryCode: "BI" },
  { code: "BMD", name: "Bermudian Dollar", countryCode: "BM" },
  { code: "BSD", name: "Bahamian Dollar", countryCode: "BS" },
  { code: "BTN", name: "Bhutanese Ngultrum", countryCode: "BT" },
  { code: "BWP", name: "Botswana Pula", countryCode: "BW" },
  { code: "BYN", name: "Belarusian Ruble", countryCode: "BY" },
  { code: "BZD", name: "Belize Dollar", countryCode: "BZ" },
  { code: "CDF", name: "Congolese Franc", countryCode: "CD" },
  { code: "CUP", name: "Cuban Peso", countryCode: "CU" },
  { code: "DJF", name: "Djiboutian Franc", countryCode: "DJ" },
  { code: "ERN", name: "Eritrean Nakfa", countryCode: "ER" },
  { code: "FKP", name: "Falkland Islands Pound", countryCode: "FK" },
  { code: "GEL", name: "Georgian Lari", countryCode: "GE" },
  { code: "GIP", name: "Gibraltar Pound", countryCode: "GI" },
  { code: "GMD", name: "Gambian Dalasi", countryCode: "GM" },
  { code: "GNF", name: "Guinean Franc", countryCode: "GN" },
  { code: "GYD", name: "Guyanese Dollar", countryCode: "GY" },
  { code: "HTG", name: "Haitian Gourde", countryCode: "HT" },
  { code: "IQD", name: "Iraqi Dinar", countryCode: "IQ" },
  { code: "IRR", name: "Iranian Rial", countryCode: "IR" },
  { code: "ISK", name: "Icelandic Krona", countryCode: "IS" },
  { code: "ILS", name: "Israeli New Shekel", countryCode: "IL" },
  { code: "KGS", name: "Kyrgyzstani Som", countryCode: "KG" },
  { code: "KMF", name: "Comorian Franc", countryCode: "KM" },
  { code: "KYD", name: "Cayman Islands Dollar", countryCode: "KY" },
  { code: "KZT", name: "Kazakhstani Tenge", countryCode: "KZ" },
  { code: "LBP", name: "Lebanese Pound", countryCode: "LB" },
  { code: "LRD", name: "Liberian Dollar", countryCode: "LR" },
  { code: "LSL", name: "Lesotho Loti", countryCode: "LS" },
  { code: "LYD", name: "Libyan Dinar", countryCode: "LY" },
  { code: "MDL", name: "Moldovan Leu", countryCode: "MD" },
  { code: "MGA", name: "Malagasy Ariary", countryCode: "MG" },
  { code: "MKD", name: "Macedonian Denar", countryCode: "MK" },
  { code: "MUR", name: "Mauritian Rupee", countryCode: "MU" },
  { code: "MVR", name: "Maldivian Rufiyaa", countryCode: "MV" },
  { code: "MWK", name: "Malawian Kwacha", countryCode: "MW" },
  { code: "MZN", name: "Mozambican Metical", countryCode: "MZ" },
  { code: "NAD", name: "Namibian Dollar", countryCode: "NA" },
  { code: "RSD", name: "Serbian Dinar", countryCode: "RS" },
  { code: "SCR", name: "Seychellois Rupee", countryCode: "SC" },
  { code: "SDG", name: "Sudanese Pound", countryCode: "SD" },
  { code: "SHP", name: "Saint Helena Pound", countryCode: "SH" },
  { code: "SLE", name: "Sierra Leone Leone", countryCode: "SL" },
  { code: "SOS", name: "Somali Shilling", countryCode: "SO" },
  { code: "SRD", name: "Surinamese Dollar", countryCode: "SR" },
  { code: "SSP", name: "South Sudanese Pound", countryCode: "SS" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", countryCode: "ST" },
  { code: "SYP", name: "Syrian Pound", countryCode: "SY" },
  { code: "SZL", name: "Eswatini Lilangeni", countryCode: "SZ" },
  { code: "TJS", name: "Tajikistani Somoni", countryCode: "TJ" },
  { code: "TMT", name: "Turkmenistani Manat", countryCode: "TM" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", countryCode: "TT" },
  { code: "TZS", name: "Tanzanian Shilling", countryCode: "TZ" },
  { code: "UZS", name: "Uzbekistani Som", countryCode: "UZ" },
  { code: "XAF", name: "Central African CFA Franc", countryCode: "CM" },
  { code: "XOF", name: "West African CFA Franc", countryCode: "SN" },
  { code: "YER", name: "Yemeni Rial", countryCode: "YE" },
  { code: "ZMW", name: "Zambian Kwacha", countryCode: "ZM" },
  { code: "AFN", name: "Afghan Afghani", countryCode: "AF" },
  { code: "MAD", name: "Moroccan Dirham", countryCode: "MA" },
  { code: "NGN", name: "Nigerian Naira", countryCode: "NG" },
  { code: "PKR", name: "Pakistani Rupee", countryCode: "PK" },
  { code: "LKR", name: "Sri Lankan Rupee", countryCode: "LK" },
  { code: "NPR", name: "Nepalese Rupee", countryCode: "NP" },
  { code: "BDT", name: "Bangladeshi Taka", countryCode: "BD" },
  { code: "KRW", name: "South Korean Won", countryCode: "KR" },
  { code: "XAU", name: "Gold (Troy Ounce)", countryCode: "UN" },
  { code: "XAG", name: "Silver (Troy Ounce)", countryCode: "UN" },
  { code: "CLF", name: "Chilean Unit of Account", countryCode: "CL" },
  { code: "GGP", name: "Guernsey Pound", countryCode: "GG" },
  { code: "IMP", name: "Isle of Man Pound", countryCode: "IM" },
  { code: "JEP", name: "Jersey Pound", countryCode: "JE" },
    { code: "MRO", name: "Mauritanian Ouguiya", countryCode: "MR" },
  { code: "MRU", name: "Mauritanian Ouguiya (New)", countryCode: "MR" },
  { code: "RWF", name: "Rwandan Franc", countryCode: "RW" },
  { code: "BOV", name: "Bolivian Mvdol", countryCode: "BO" },
  { code: "CHE", name: "WIR Euro", countryCode: "CH" },
  { code: "CHW", name: "WIR Franc", countryCode: "CH" },
  { code: "COU", name: "Unidad de Valor Real", countryCode: "CO" },
  { code: "CUC", name: "Cuban Convertible Peso", countryCode: "CU" },
  { code: "MXV", name: "Mexican Unidad de Inversion", countryCode: "MX" },
  { code: "USN", name: "US Dollar (Next Day)", countryCode: "US" },
  { code: "UYI", name: "Uruguay Peso en Unidades Indexadas", countryCode: "UY" },
  { code: "VED", name: "Venezuelan Digital Bolívar", countryCode: "VE" },
  { code: "ZWL", name: "Zimbabwean Dollar", countryCode: "ZW" },
  { code: "SVC", name: "Salvadoran Colón", countryCode: "SV" },
  { code: "TVD", name: "Tuvalu Dollar", countryCode: "TV" },
  { code: "KID", name: "Kiribati Dollar", countryCode: "KI" },
  { code: "CVE", name: "Cape Verdean Escudo", countryCode: "CV" },
  { code: "XDR", name: "Special Drawing Rights", countryCode: "UN" },
  { code: "XPD", name: "Palladium", countryCode: "UN" },
  { code: "XPT", name: "Platinum", countryCode: "UN" },
];
export default currencies;